Repository nestjs-addons/in-memory-db, pull requests merged in 2019-08, with the labels that each got.

#6 refactor: use dictionary to maintain records
  lib/services/in-memory-db.service.ts
  package-lock.json
Labels: bug, documentation

#21 feat: implement configuration via forRoot
  lib/in-memory-db.module.ts
  lib/interfaces/in-memory-db-config.ts
  lib/interfaces/index.ts
  lib/services/in-memory-db.service.ts
  package-lock.json
  package.json
Labels: enhancement

#31 feat: add async methods to CRUD operations
  lib/services/in-memory-db.service.spec.ts
  lib/services/in-memory-db.service.ts
  package-lock.json
  package.json
Labels: enhancement, wip

#64 feat: implementing forFeature
  README.md
  lib/common/in-memory-db.constants.ts
  lib/common/in-memory-db.decorators.ts
  lib/common/in-memory-db.utils.spec.ts
  lib/common/in-memory-db.utils.ts
  lib/common/index.ts
  lib/factories/in-memory-db-service.factory.ts
  lib/factories/index.ts
  lib/in-memory-db.module.ts
  lib/index.ts
  lib/interfaces/in-memory-db-config.ts
  lib/providers/in-memory-db-for-feature.providers.spec.ts
  lib/providers/in-memory-db-for-feature.providers.ts
  lib/providers/in-memory-db-for-root.providers.spec.ts
  lib/providers/in-memory-db-for-root.providers.ts
  lib/providers/index.ts
  lib/services/in-memory-db.service.spec.ts
  lib/services/in-memory-db.service.ts
Labels: enhancement
